config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root 'gossips#index'
  get '/team' => 'team#team_section'
  get '/contact' => 'contact#contact_section'
  get '/welcome/display' => 'welcome#welcome_display'
  get '/welcome/:id' => 'welcome#welcome_customize' # route qui va me permettre de récup l'entrée dans mon URL ex: http://localhost:3000/welcome/rintintin
  resources :users
  resources :gossips
  resources :cities
  resources :gossips do
    resources :comments
  end
  delete '/logout' => 'sessions#destroy', as: 'logout'
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    validates :title, presence: true # rend la présence du titre obligatoire
    validates :title, length: { in: 3..3003 }
    validates :content, presence: true

    belongs_to :user, required: false
    belongs_to :tag_gossip, required: false
    has_many :tags, through: :tag_gossips
    has_many :comments
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
   before_action :authenticate_user
   include GossipsHelper
  
    def index
      @all_gossips = Gossip.all
    end


    def show
      @gossip = Gossip.find(params[:id])
    end
    
    def new
        @gossip = Gossip.new('title' => params[:title],
        'content' => params[:content])
    end

    def create
        @user = current_user
        @gossip = Gossip.new('title' => params[:title],
                             'content' => params[:content], 'user_id' => @user.id)
        if @gossip.save
          redirect_to gossips_path
        else
          render :new, status: :unprocessable_entity
        end
    end

    def edit
    @gossip = Gossip.find(params[:id]) #
      if verify_user?
        render :edit
      else
        redirect_to gossips_path
      end
    end
    
    def update
      @gossip = Gossip.find(params[:id])
      if verify_user? && @gossip.update(title: params[:title], content: params[:content])
        redirect_to gossips_path
      else
        render :edit
      end
    end

    def destroy
    @gossip = Gossip.find(params[:id]) 
      if verify_user?
       @gossip.destroy
       redirect_to root_path, notice: "Le potin a été supprimé avec succès"
      else
        redirect_to gossips_path, notice: "Tu dois être connecté"
      end
    end

    private

    def authenticate_user
      unless current_user
        flash[:danger] = "Please log in."
        redirect_to new_session_path
      end
    end
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
    def verify_user?
        if current_user.id == @gossip.user_id
            return true
        else
            return false
        end
    end
end

app/views/gossips/edit.html.erb
<html>
  <body>
    <!-- .. -->

    <%= form_tag url_for(action: 'update'), method: "PATCH" do %>

      <%= label_tag 'Titre' %>
      <%= text_field_tag 'title', @gossip.title %>
      <br /> <br />

      <%= label_tag 'Contenu' %>
      <%= text_area_tag 'content', @gossip.content %>
      <br /> <br />

      <%= submit_tag "Modifier le commérage" %>

      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <% end %>

    <!-- ... -->
  </body>
</html>

app/views/gossips/index.html.erb
<div class="mx-auto" style="width: 200px;">
  Bonjour les djeuns !
</div><br>
<div class="mx-auto" style="width: 200px;">
  J'ai pleeeeeeiiiiiiiiiin de choses à vous raconter !
</div><br>
<div class="mx-auto" style="width: 200px;">
<a href="/gossips/new" class="btn btn-primary">Lien pour commérer</a>

</div><br>


    <div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @all_gossips.each do |gossip| %>
        <div class="col">
          <div class="card ">
            <div class="card shadow p-3 bg-white rounded" style="">
              <div class="card-body">
                <h5 class="card-title"><%= gossip.title %></h5>
                <h6 class="card-subtitle mb-2 text-muted"> de <%= gossip.content %></h6>
                <a href="/gossips/<%= gossip.id %>" class="btn btn-primary">Lien vers le potin <%= gossip.id %></a>
              </div>
            </div>
          </div>
        </div>
    <% end%>
    </div>
  </div>
  </body>
</div>

app/views/gossips/new.html.erb
<html>
  <body>
    <!-- ... -->

    <%= form_tag url_for(action: 'create'), method: "POST" do %>

      <%= label_tag 'Titre' %>
      <%= text_field_tag 'title', @gossip.title %>
      <br /> <br />

      <%= label_tag 'Contenu' %>
      <%= text_area_tag 'content', @gossip.content %>
      <br /> <br />

      <%= submit_tag "Soumettre le commérage" %>

      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <% end %>

    <!-- ... -->
  </body>
</html>

app/views/gossips/show.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
  </head>

  <body>
  <div class="container">
    <br>
    <h1>BIENVENUE !</h1>
    <br>
    <div class="card">
      <div class="card-header">
        Voici l'index du potin n°<%= @gossip.id %>
      </div>
      <div class="card-body">
        <h5 class="card-title">Le titre du gossip est <%= @gossip.title %></h5><br>
        <p class="card-text">Le nom de son auteur est le suivant : <%= @gossip.user.first_name %></p>
        <p class="card-text">Son contenu est le suivant : <%= @gossip.content %></p>
        <p class="card-text">Sa ville est la suivante : <%= @gossip.user.city.name %></p>
        <% name_user = @gossip.user.first_name %>
        <a href="/users/<%= @gossip.user.id %>"class="btn btn-primary">Voir le profil de son auteur</a>
        <a href="/cities/<%= @gossip.user.id %>"class="btn btn-primary">Voir la ville de l'auteur</a>
        <a href="/gossips/<%= params[:id] %>/edit"class="btn btn-danger">Editer le potin</a>
        <%= button_to "Destroy", gossip_path(@gossip), method: :delete %>
      </div>
    </div>
  </div>
  </body>

</html>